### ISSUE TITLE
Can't register group chat as main chat

### ISSUE THREAD

**Issue by BjoernPetersen** [OpenAlcoholics/regular_dicers_bot#10]
The admin check is performed with the hard-coded chat ID of a direct chat.

**Comment by Chabare** [comment]
Do we need an admin chat anyway?
I mean, it was only there to work around #2 (`/remind_all`)

I agree, that the [hardcoded id](https://github.com/OpenAlcoholics/regular_dicers_bot/blob/develop/dicers_bot/bot.py#L19) should be removed

**Comment by BjoernPetersen** [comment]
I think the only reason a "main" chat (however we configure it) is for the calendar integration
