### ISSUE TITLE
(De-)serialization is broken

### ISSUE THREAD

**Issue by Chabare** [OpenAlcoholics/regular_dicers_bot#17]
Since the introduction of classes and a series of unfortunate events, the (de-)serialize process misses some fields.

e.g. [User](https://github.com/OpenAlcoholics/regular_dicers_bot/blob/feature/mute_spam/dicers_bot/bot.py#L41-L83) which doesn't even have a `deserialize` method.

**Comment by BjoernPetersen** [comment]
Is this issue fixed with #16 ?

**Comment by Chabare** [comment]
Yeah, it definitely should be.
