### ISSUE TITLE
Scheduled messages aren't working

### ISSUE THREAD

**Issue by BjoernPetersen** [OpenAlcoholics/regular_dicers_bot#2]

**Comment by Chabare** [comment]
Works as intended, just not in TZ Europe/Berlin

**Comment by Chabare** [comment]
Apparently there was no build (-> deploy) since 3fda791d27efa550029d78cf4dbdc050a9dff89c. The fix was since included in the repo. CircleCI seems to have an outage atm due to the recent github outage.

**Comment by BjoernPetersen** [comment]
I'm pretty sure CircleCI is fine, GitHub just has to invoke almost a day's worth of Webhooks right now. According to the CircleCI guys, they're overprovisioning until they are confident the backlog is done.

**Comment by Chabare** [comment]
Weird, I just checked and d3fda791 should be included in `:latest-develop` but isn't.
