### ISSUE TITLE
Remove roll from event attendee if he presses Nicht Dabei

### ISSUE THREAD

**Issue by BjoernPetersen** [OpenAlcoholics/regular_dicers_bot#29]
Users can still press `Dabei` or `Nicht Dabei` when the dice keyboard is already shown. If a user presses `Nicht Dabei` after they already selected their die roll, the roll should be cleared, because the user can't edit their answer anymore if they are not attending.

This is of course a rather illogical edge case, but users are dumb.

**Comment by Chabare** [comment]
I fucking hate users...
