### ISSUE TITLE
Reset on mondays before the event

### ISSUE THREAD

**Issue by BjoernPetersen** [OpenAlcoholics/regular_dicers_bot#39]
Additionally to the reset on tuesdays, we should sprinkle in another one on mondays before starting an event.

**Comment by Chabare** [comment]
Should we perform the reset via another scheduled action (like this: https://github.com/OpenAlcoholics/regular_dicers_bot/blob/feature/issue-39/main.py#L20 https://github.com/OpenAlcoholics/regular_dicers_bot/blob/feature/issue-39/main.py#L27)?

**Comment by BjoernPetersen** [comment]
I'd say so. Though maybe at 14:30 or so.
