### ISSUE TITLE
Show history for users

### ISSUE THREAD

**Issue by torbencarstens** [OpenAlcoholics/regular_dicers_bot#51]
`/history [me]` -> Shows payment/attendance history for each/individual user

**Comment by Chabare** [comment]
# Charts

- (Line) Attendance over time
- (Bar) Overall attendance per user + Line with overall attendance  
- (Bar) Average die roll per user + Line with overall average
- (Area or Pie) Total sum paid

**Comment by Chabare** [comment]
example: ![average_attendance](https://user-images.githubusercontent.com/7738181/53796527-a9bb8980-3f34-11e9-8bd8-eb0f4bd8aac6.png)

**Comment by Chabare** [comment]
![bar](https://user-images.githubusercontent.com/7738181/53799361-7f6cca80-3f3a-11e9-8638-0813e5055df6.png)
![pie](https://user-images.githubusercontent.com/7738181/53799286-53514980-3f3a-11e9-95ca-22d29b47fb61.png)
